from datetime import date, datetime, timezone
from sqlalchemy import String, Text, Date, Integer, Float, ForeignKey, Boolean, UniqueConstraint, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, UUIDPrimaryKeyMixin, TimestampMixin
from app.models.enums import *

class User(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='users'; email:Mapped[str]=mapped_column(String(320),unique=True,index=True); display_name:Mapped[str]=mapped_column(String(100)); password_hash:Mapped[str]=mapped_column(String(255)); is_active:Mapped[bool]=mapped_column(Boolean,default=True); library:Mapped[list['UserMedia']]=relationship(back_populates='user',cascade='all, delete-orphan')
class Media(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='media'; media_type:Mapped[str]=mapped_column(String(30),index=True); title:Mapped[str]=mapped_column(String(500),index=True); description:Mapped[str|None]=mapped_column(Text); release_year:Mapped[int|None]=mapped_column(Integer,index=True); release_date:Mapped[date|None]=mapped_column(Date); status:Mapped[str]=mapped_column(String(30),default='unknown'); original_language:Mapped[str|None]=mapped_column(String(16)); cover_url:Mapped[str|None]=mapped_column(String(2048)); metadata_:Mapped[dict]=mapped_column('metadata',JSON,default=dict); external_ids:Mapped[list['MediaExternalId']]=relationship(back_populates='media',cascade='all, delete-orphan'); titles:Mapped[list['MediaTitle']]=relationship(back_populates='media',cascade='all, delete-orphan'); genres:Mapped[list['MediaGenre']]=relationship(back_populates='media',cascade='all, delete-orphan'); units:Mapped[list['MediaUnit']]=relationship(back_populates='media',cascade='all, delete-orphan'); library:Mapped[list['UserMedia']]=relationship(back_populates='media',cascade='all, delete-orphan')
class MediaExternalId(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='media_external_ids'; __table_args__=(UniqueConstraint('provider','external_id'),); media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE'),index=True); provider:Mapped[str]=mapped_column(String(80),index=True); external_id:Mapped[str]=mapped_column(String(255)); url:Mapped[str|None]=mapped_column(String(2048)); media:Mapped[Media]=relationship(back_populates='external_ids')
class MediaTitle(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='media_titles'; media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE')); title:Mapped[str]=mapped_column(String(500)); language_code:Mapped[str|None]=mapped_column(String(16)); title_type:Mapped[str]=mapped_column(String(30)); media:Mapped[Media]=relationship(back_populates='titles')
class MediaGenre(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='media_genres'; media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(100)); media:Mapped[Media]=relationship(back_populates='genres')
class MediaUnit(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='media_units'; media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE'),index=True); parent_id:Mapped[str|None]=mapped_column(ForeignKey('media_units.id',ondelete='CASCADE')); unit_type:Mapped[str]=mapped_column(String(30)); number:Mapped[float]=mapped_column(Float); title:Mapped[str|None]=mapped_column(String(500)); release_date:Mapped[date|None]=mapped_column(Date); duration_seconds:Mapped[int|None]=mapped_column(Integer); metadata_:Mapped[dict]=mapped_column('metadata',JSON,default=dict); media:Mapped[Media]=relationship(back_populates='units')
class UserMedia(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='user_media'; __table_args__=(UniqueConstraint('user_id','media_id'),); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE')); status:Mapped[str]=mapped_column(String(30),default='planned'); progress:Mapped[float]=mapped_column(Float,default=0); total:Mapped[float|None]=mapped_column(Float); rating:Mapped[float|None]=mapped_column(Float); notes:Mapped[str|None]=mapped_column(Text); source:Mapped[str]=mapped_column(String(30),default='manual'); last_source_updated_at:Mapped[datetime]=mapped_column(default=lambda:datetime.now(timezone.utc)); user:Mapped[User]=relationship(back_populates='library'); media:Mapped[Media]=relationship(back_populates='library')
class UserProgress(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='user_progress'; user_media_id:Mapped[str]=mapped_column(ForeignKey('user_media.id',ondelete='CASCADE')); value:Mapped[float]=mapped_column(Float); unit:Mapped[str]=mapped_column(String(30)); source:Mapped[str]=mapped_column(String(30)); occurred_at:Mapped[datetime]=mapped_column(default=lambda:datetime.now(timezone.utc))
class UserList(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='user_lists'; __table_args__=(UniqueConstraint('user_id','name'),); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); name:Mapped[str]=mapped_column(String(150)); description:Mapped[str|None]=mapped_column(Text); is_public:Mapped[bool]=mapped_column(Boolean,default=False)
class UserListItem(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__='user_list_items'; __table_args__=(UniqueConstraint('user_list_id','media_id'),); user_list_id:Mapped[str]=mapped_column(ForeignKey('user_lists.id',ondelete='CASCADE')); media_id:Mapped[str]=mapped_column(ForeignKey('media.id',ondelete='CASCADE')); position:Mapped[int]=mapped_column(Integer,default=0)
